name: Convert Markdown to PDF

on:
  push:
    paths:
      - 'docs/**/*.md'
  workflow_dispatch:

jobs:
  convert-md-to-pdf:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Pandoc and xelatex dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc \
            texlive-xetex texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

      - name: Create symlink for docs
        run: |
          if [ ! -d /docs ]; then
            sudo ln -s "${{ github.workspace }}/docs" /docs
          fi

      - name: Convert Markdown files to PDF
        run: |
          echo "Buscando arquivos Markdown em 'docs'..."
          find docs -type f -name "*.md" | while read mdfile; do
            pdffile="${mdfile%.md}.pdf"
            echo "Convertendo '$mdfile' para '$pdffile'..."
            pandoc "$mdfile" -o "$pdffile" --resource-path=. --pdf-engine=xelatex -V mainfont="DejaVu Sans"
          done

      - name: Commit and push PDFs
        run: |
          echo "Verificando alterações..."
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # Adiciona os arquivos PDF, tratando nomes com espaços corretamente
          find docs -type f -name "*.pdf" -print0 | xargs -0 git add
          if ! git diff --cached --quiet; then
            echo "Alterações encontradas. Comitando..."
            git commit -m "Auto: Convert Markdown to PDF [skip ci]"
            git push
          else
            echo "Nenhuma alteração encontrada. Nada a comitar."
          fi
